<?php

namespace Database\Seeders;

use App\Models\Lead;
use Illuminate\Database\Seeder;

class LeadSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $leads = [
            [
                'company_name' => 'Adventure Seekers Tours',
                'website' => 'https://adventureseekers.com',
                'email' => 'info@adventureseekers.com',
                'phone' => '+1-555-0101',
                'country' => 'USA',
                'city' => 'Denver',
                'contact_name' => 'John Smith',
                'contact_position' => 'CEO',
                'contact_email' => 'john@adventureseekers.com',
                'business_type' => 'tour_operator',
                'tour_types' => ['adventure', 'eco-tourism', 'group'],
                'target_markets' => ['USA', 'Canada', 'UK'],
                'annual_volume' => 5000,
                'status' => 'new',
                'source' => 'web_scraper',
                'source_url' => 'https://google.com/search?q=adventure+tours',
                'quality_score' => 4,
                'notes' => 'Specializes in mountain and outdoor adventures',
            ],
            [
                'company_name' => 'Cultural Heritage Travel',
                'website' => 'https://culturalheritage.de',
                'email' => 'contact@culturalheritage.de',
                'phone' => '+49-30-12345678',
                'country' => 'Germany',
                'city' => 'Berlin',
                'contact_name' => 'Anna Mueller',
                'contact_position' => 'Sales Manager',
                'contact_email' => 'anna.mueller@culturalheritage.de',
                'business_type' => 'dmc',
                'tour_types' => ['cultural', 'educational', 'religious'],
                'target_markets' => ['Germany', 'Austria', 'Switzerland'],
                'annual_volume' => 3000,
                'status' => 'qualified',
                'source' => 'directory',
                'quality_score' => 5,
                'notes' => 'Focus on historical and UNESCO sites',
            ],
            [
                'company_name' => 'Luxury Escapes International',
                'website' => 'https://luxuryescapes.co.uk',
                'email' => 'bookings@luxuryescapes.co.uk',
                'phone' => '+44-20-7946-0958',
                'country' => 'UK',
                'city' => 'London',
                'contact_name' => 'James Wilson',
                'contact_position' => 'Director',
                'contact_email' => 'james@luxuryescapes.co.uk',
                'business_type' => 'travel_agency',
                'tour_types' => ['luxury', 'honeymoon', 'wellness'],
                'target_markets' => ['UK', 'USA', 'UAE'],
                'annual_volume' => 8000,
                'certifications' => ['ABTA', 'IATA'],
                'status' => 'contacted',
                'source' => 'referral',
                'quality_score' => 5,
                'notes' => 'High-end clientele, excellent potential',
            ],
            [
                'company_name' => 'Budget Backpackers',
                'website' => 'https://budgetbackpackers.com.au',
                'email' => 'info@budgetbackpackers.com.au',
                'phone' => '+61-2-9876-5432',
                'country' => 'Australia',
                'city' => 'Sydney',
                'contact_name' => 'Sarah Johnson',
                'contact_position' => 'Operations Manager',
                'business_type' => 'ota',
                'tour_types' => ['budget', 'adventure', 'family'],
                'target_markets' => ['Australia', 'New Zealand', 'Asia'],
                'annual_volume' => 12000,
                'status' => 'responded',
                'source' => 'csv_import',
                'quality_score' => 3,
                'notes' => 'Large volume but lower margins',
            ],
            [
                'company_name' => 'Asia Discovery Tours',
                'website' => 'https://asiadiscovery.jp',
                'email' => 'sales@asiadiscovery.jp',
                'phone' => '+81-3-1234-5678',
                'country' => 'Japan',
                'city' => 'Tokyo',
                'contact_name' => 'Yuki Tanaka',
                'contact_position' => 'President',
                'contact_email' => 'tanaka@asiadiscovery.jp',
                'business_type' => 'tour_operator',
                'tour_types' => ['cultural', 'family', 'group'],
                'target_markets' => ['Japan', 'China', 'South Korea'],
                'annual_volume' => 7000,
                'certifications' => ['JATA'],
                'status' => 'new',
                'source' => 'manual',
                'quality_score' => 4,
            ],
            [
                'company_name' => 'French Riviera Tours',
                'website' => 'https://frenchriviera.fr',
                'email' => 'contact@frenchriviera.fr',
                'phone' => '+33-4-93-12-34-56',
                'country' => 'France',
                'city' => 'Nice',
                'contact_name' => 'Pierre Dubois',
                'contact_position' => 'Managing Director',
                'business_type' => 'dmc',
                'tour_types' => ['luxury', 'cultural', 'wellness'],
                'target_markets' => ['France', 'USA', 'Russia'],
                'annual_volume' => 4500,
                'status' => 'negotiating',
                'source' => 'web_scraper',
                'quality_score' => 4,
                'notes' => 'In final contract discussion phase',
            ],
            [
                'company_name' => 'Eco Adventures Global',
                'website' => 'https://ecoadventures.com',
                'email' => 'hello@ecoadventures.com',
                'phone' => '+1-415-555-0123',
                'country' => 'USA',
                'city' => 'San Francisco',
                'contact_name' => 'Emily Green',
                'contact_position' => 'Founder',
                'contact_email' => 'emily@ecoadventures.com',
                'business_type' => 'tour_operator',
                'tour_types' => ['eco-tourism', 'adventure', 'educational'],
                'target_markets' => ['USA', 'Canada', 'Europe'],
                'annual_volume' => 3500,
                'certifications' => ['ASTA', 'Green Tourism'],
                'status' => 'on_hold',
                'source' => 'referral',
                'quality_score' => 3,
                'notes' => 'Waiting for their Q2 budget approval',
            ],
            [
                'company_name' => 'MICE Solutions Inc',
                'website' => 'https://micesolutions.com',
                'email' => 'corporate@micesolutions.com',
                'phone' => '+1-212-555-0199',
                'country' => 'USA',
                'city' => 'New York',
                'contact_name' => 'Robert Taylor',
                'contact_position' => 'VP Sales',
                'contact_email' => 'rtaylor@micesolutions.com',
                'business_type' => 'consolidator',
                'tour_types' => ['mice', 'corporate', 'incentive'],
                'target_markets' => ['USA', 'Global'],
                'annual_volume' => 15000,
                'certifications' => ['MPI', 'IATA'],
                'status' => 'qualified',
                'source' => 'directory',
                'quality_score' => 5,
                'notes' => 'Major corporate events organizer',
            ],
            [
                'company_name' => 'Family Fun Vacations',
                'website' => 'https://familyfunvacations.ca',
                'email' => 'info@familyfunvacations.ca',
                'phone' => '+1-416-555-0145',
                'country' => 'Canada',
                'city' => 'Toronto',
                'contact_name' => 'Michael Brown',
                'contact_position' => 'Owner',
                'business_type' => 'travel_agency',
                'tour_types' => ['family', 'budget', 'theme parks'],
                'target_markets' => ['Canada', 'USA'],
                'annual_volume' => 6000,
                'status' => 'not_interested',
                'source' => 'manual',
                'quality_score' => 2,
                'notes' => 'Declined - focus on domestic only',
            ],
            [
                'company_name' => 'Senior Travel Club',
                'website' => 'https://seniortravelclub.com',
                'email' => 'reservations@seniortravelclub.com',
                'phone' => '+1-305-555-0178',
                'country' => 'USA',
                'city' => 'Miami',
                'contact_name' => 'Barbara Martinez',
                'contact_position' => 'Travel Director',
                'contact_email' => 'barbara@seniortravelclub.com',
                'business_type' => 'tour_operator',
                'tour_types' => ['cultural', 'leisure', 'river cruises'],
                'target_markets' => ['USA'],
                'annual_volume' => 4000,
                'status' => 'new',
                'source' => 'csv_import',
                'quality_score' => 3,
            ],
        ];

        foreach ($leads as $leadData) {
            Lead::create(array_merge($leadData, [
                'assigned_to' => 1, // Assign to first user
            ]));
        }
    }
}
