<?php

namespace App\Filament\Resources\Bookings\RelationManagers;

use App\Models\OctobankPayment;
use Filament\Actions\Action;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class OctobankPaymentsRelationManager extends RelationManager
{
    protected static string $relationship = 'octobankPayments';

    protected static ?string $title = 'Payment Links';

    protected static ?string $modelLabel = 'Payment Link';

    protected static ?string $pluralModelLabel = 'Payment Links';

    public function isReadOnly(): bool
    {
        return true; // Links are generated via the header action, not inline here
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('purpose')
                    ->label('Purpose')
                    ->badge()
                    ->color(fn (string $value): string => match ($value) {
                        'deposit'      => 'warning',
                        'balance'      => 'info',
                        'full_payment' => 'success',
                        'custom'       => 'gray',
                        default        => 'gray',
                    })
                    ->formatStateUsing(fn (?string $state): string => match ($state) {
                        'deposit'      => 'Deposit',
                        'balance'      => 'Balance',
                        'full_payment' => 'Full Payment',
                        'custom'       => 'Custom',
                        default        => $state ?? '—',
                    }),

                TextColumn::make('amount_usd')
                    ->label('USD')
                    ->prefix('$')
                    ->numeric(decimalPlaces: 2)
                    ->placeholder('—'),

                TextColumn::make('amount')
                    ->label('UZS')
                    ->numeric(decimalPlaces: 0, thousandsSeparator: ' ')
                    ->suffix(' UZS'),

                TextColumn::make('fx_rate_used')
                    ->label('FX Rate')
                    ->numeric(decimalPlaces: 2)
                    ->placeholder('—'),

                TextColumn::make('status')
                    ->label('Status')
                    ->badge()
                    ->color(fn (string $value): string => match ($value) {
                        'succeeded'      => 'success',
                        'waiting'        => 'warning',
                        'created'        => 'gray',
                        'failed'         => 'danger',
                        'cancelled'      => 'danger',
                        'refunded'       => 'info',
                        'partial_refund' => 'info',
                        default          => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'created'        => 'Created',
                        'waiting'        => 'Awaiting Payment',
                        'succeeded'      => 'Paid',
                        'failed'         => 'Failed',
                        'refunded'       => 'Refunded',
                        'partial_refund' => 'Partial Refund',
                        'cancelled'      => 'Cancelled',
                        default          => $state,
                    }),

                TextColumn::make('generatedByUser.name')
                    ->label('Generated By')
                    ->placeholder('—')
                    ->getStateUsing(fn (OctobankPayment $record): string => $record->generated_by
                        ? (\App\Models\User::find($record->generated_by)?->name ?? "User #{$record->generated_by}")
                        : '—'
                    ),

                TextColumn::make('created_at')
                    ->label('Created')
                    ->dateTime('d M Y H:i')
                    ->sortable(),

                TextColumn::make('expires_at')
                    ->label('Expires')
                    ->dateTime('d M Y H:i')
                    ->placeholder('—')
                    ->color(fn (?string $state): string => $state && now()->isAfter($state) ? 'danger' : 'gray'),

                TextColumn::make('webhook_received_at')
                    ->label('Paid At')
                    ->dateTime('d M Y H:i')
                    ->placeholder('—'),
            ])
            ->defaultSort('created_at', 'desc')
            ->recordActions([
                Action::make('open_link')
                    ->label('Open')
                    ->icon('heroicon-o-arrow-top-right-on-square')
                    ->url(fn (OctobankPayment $record): ?string => $record->octo_payment_url)
                    ->openUrlInNewTab()
                    ->visible(fn (OctobankPayment $record): bool => (bool) $record->octo_payment_url),
            ])
            ->emptyStateHeading('No payment links yet')
            ->emptyStateDescription('Generate a payment link using the "Generate Payment Link" button above.')
            ->striped();
    }
}
